version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment: &db_env
          POSTGRES_DB: pg_service_template_db_1
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    pg_service_template-container:
        build:
          context: .
          dockerfile: Dockerfile
        privileged: true
        environment:
          <<: *db_env
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /pg_service_template/.ccache
          CORES_DIR: /cores
          OWN_URL: http://192.168.0.52:8080/v1/compress-audio
          BALANCER_URL: http://192.168.0.60:8080/v1/imalive
        volumes:
          - .:/pg_service_template:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /pg_service_template
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
