openapi: 3.0.3
info:
  title: BeatsByte - MP3 Compression Service
  description: A service for compressing MP3 files.
  version: 1.0.0
paths:
  /compress-audio:
    post:
      description: Compress an mp3 file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The MP3 file to be compressed
      responses:
        '200':
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request, possibly due to an invalid file format or size.
